"""add users and auth roles

Revision ID: 7a8de900ca34
Revises: 3965854eb1a4
Create Date: 2026-05-16 20:59:21.127724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8de900ca34'
down_revision: Union[str, None] = '3965854eb1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('document_chunks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document_chunks', 'users', ['user_id'], ['id'])
    op.add_column('log_uploads', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'log_uploads', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'log_uploads', type_='foreignkey')
    op.drop_column('log_uploads', 'user_id')
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_column('document_chunks', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
