import React, { useState, useEffect, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Terminal, Activity, ShieldAlert, Settings, LogOut, Clock, FileText, ChevronDown, ChevronUp, Copy, Check, Download } from 'lucide-react';
import axios from 'axios';
import API_BASE from '../config';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from 'recharts';
import toast from 'react-hot-toast';
import UploadZone from '../components/UploadZone';
import { useAuth } from '../context/AuthContext';
import { useNavigate } from 'react-router-dom';
import ThemeToggle from '../components/ThemeToggle';

const SEVERITY_COLORS = { CRITICAL: '#d94f4f', ERROR: '#e87461', WARNING: '#e8a33d', INFO: '#2d9d78' };

const SeverityBadge = ({ severity }) => {
  const cls = (() => {
    switch (severity?.toUpperCase()) {
      case 'CRITICAL': case 'ERROR': return 'badge-error';
      case 'WARNING': return 'badge-accent';
      default: return 'badge-success';
    }
  })();
  return <span className={`badge ${cls}`}>{severity || '—'}</span>;
};

const CopyButton = ({ text }) => {
  const [copied, setCopied] = useState(false);
  const handleCopy = () => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    toast.success('Copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <button onClick={handleCopy} className="btn-ghost" style={{ padding: '0.2rem 0.5rem', fontSize: '0.75rem' }}>
      {copied ? <Check size={12} /> : <Copy size={12} />} {copied ? 'Copied' : 'Copy'}
    </button>
  );
};

const exportAsMarkdown = (result) => {
  const a = result.analysis || {};
  const md = `# Log Analysis Report\n**File:** ${result.filename || 'Unknown'}\n**Severity:** ${a.severity || 'Unknown'}\n**Date:** ${new Date().toLocaleString()}\n\n## Summary\n${a.issue_summary || '—'}\n\n## Root Cause\n${a.root_cause || '—'}\n\n## Remediation\n${a.remediation || '—'}\n\n---\n*Generated by LOG2ACTION*\n`;
  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `log-report-${result.filename || 'analysis'}.md`;
  link.click();
  URL.revokeObjectURL(url);
  toast.success('Report downloaded');
};


/* ── Full-width analysis result ── */
const AnalysisResult = ({ result, onReset }) => {
  const a = result.analysis || {};
  return (
    <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="card" style={{ padding: '2rem' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '0.5rem' }}>
        <h2 style={{ fontSize: '1.25rem', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <Activity size={20} color="var(--accent)" /> Intelligence Report
        </h2>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <SeverityBadge severity={a.severity} />
          <button onClick={() => exportAsMarkdown(result)} className="btn-ghost" style={{ padding: '0.2rem 0.5rem', fontSize: '0.75rem' }}>
            <Download size={12} /> Export
          </button>
        </div>
      </div>

      {/* Summary — full width */}
      <div style={{ marginBottom: '1.5rem' }}>
        <label style={{ fontSize: '0.7rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.5px', color: 'var(--text-tertiary)' }}>Summary</label>
        <p style={{ marginTop: '0.3rem', fontSize: '0.95rem', lineHeight: 1.6 }}>{a.issue_summary || '—'}</p>
      </div>

      {/* Root Cause — full width */}
      <div style={{ marginBottom: '1.5rem' }}>
        <label style={{ fontSize: '0.7rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.5px', color: 'var(--text-tertiary)' }}>Root Cause</label>
        <div style={{ marginTop: '0.4rem', padding: '1rem', borderRadius: '10px', background: 'var(--bg-primary)', border: '1px solid var(--border-subtle)' }}>
          <p style={{ fontSize: '0.9rem', lineHeight: 1.7, whiteSpace: 'pre-wrap', wordBreak: 'break-word', color: 'var(--text-secondary)' }}>{a.root_cause || '—'}</p>
        </div>
      </div>

      {/* Remediation — full width, highlighted */}
      <div style={{ marginBottom: '1.5rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <label style={{ fontSize: '0.7rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.5px', color: 'var(--text-tertiary)' }}>Remediation</label>
          {a.remediation && <CopyButton text={a.remediation} />}
        </div>
        <div style={{ marginTop: '0.4rem', padding: '1rem', borderRadius: '10px', background: 'rgba(45,157,120,0.05)', border: '1px solid rgba(45,157,120,0.15)' }}>
          <p style={{ fontSize: '0.9rem', lineHeight: 1.7, whiteSpace: 'pre-wrap', wordBreak: 'break-word', color: 'var(--success)' }}>{a.remediation || '—'}</p>
        </div>
      </div>

      <button onClick={onReset} className="btn-secondary" style={{ width: '100%' }}>Analyze another log</button>
    </motion.div>
  );
};


/* ── Expandable history item ── */
const HistoryItem = ({ item, isLast }) => {
  const [open, setOpen] = useState(false);
  const a = item.analysis;
  const time = item.created_at ? new Date(item.created_at).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : '';

  return (
    <div style={{ borderBottom: isLast ? 'none' : '1px solid var(--border-subtle)' }}>
      <button onClick={() => setOpen(!open)} style={{ width: '100%', display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0.75rem 1rem', background: 'transparent', borderRadius: 0, color: 'var(--text-primary)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', textAlign: 'left' }}>
          <FileText size={14} color="var(--text-tertiary)" />
          <div>
            <div style={{ fontSize: '0.85rem', fontWeight: 600 }}>{item.filename}</div>
            <div style={{ fontSize: '0.7rem', color: 'var(--text-tertiary)' }}>{time}</div>
          </div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
          {a && <SeverityBadge severity={a.severity} />}
          {open ? <ChevronUp size={14} color="var(--text-tertiary)" /> : <ChevronDown size={14} color="var(--text-tertiary)" />}
        </div>
      </button>
      <AnimatePresence>
        {open && a && (
          <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} style={{ overflow: 'hidden', padding: '0 1rem 0.75rem' }}>
            <div style={{ padding: '0.75rem', borderRadius: '8px', background: 'var(--bg-primary)', border: '1px solid var(--border-subtle)', fontSize: '0.8rem', lineHeight: 1.5 }}>
              <p>{a.issue_summary}</p>
              {a.remediation && <p style={{ marginTop: '0.5rem', color: 'var(--success)' }}>{a.remediation}</p>}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

/* ── Compact severity chart + history bar ── */
const HistorySidebar = ({ history, historyLoading }) => {
  const chartData = useMemo(() => {
    const counts = {};
    history.forEach(h => {
      const sev = h.analysis?.severity || 'INFO';
      counts[sev] = (counts[sev] || 0) + 1;
    });
    return Object.entries(counts).map(([name, value]) => ({ name, value }));
  }, [history]);

  return (
    <div className="card" style={{ overflow: 'hidden' }}>
      {/* Header row with inline chart */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0.75rem 1rem', borderBottom: '1px solid var(--border-subtle)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.85rem', fontWeight: 700 }}>
          <Clock size={14} color="var(--accent)" /> Recent analyses
        </div>
        {chartData.length > 0 && (
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            {chartData.map(d => (
              <div key={d.name} style={{ display: 'flex', alignItems: 'center', gap: '0.25rem', fontSize: '0.7rem' }}>
                <div style={{ width: 6, height: 6, borderRadius: '50%', background: SEVERITY_COLORS[d.name] || '#666' }} />
                <span style={{ color: 'var(--text-tertiary)' }}>{d.name}</span>
                <span style={{ fontWeight: 700 }}>{d.value}</span>
              </div>
            ))}
          </div>
        )}
      </div>
      {/* List */}
      {historyLoading ? (
        <div style={{ padding: '1.5rem', textAlign: 'center', color: 'var(--text-tertiary)', fontSize: '0.85rem' }}>Loading...</div>
      ) : history.length === 0 ? (
        <div style={{ padding: '1.5rem', textAlign: 'center', color: 'var(--text-tertiary)', fontSize: '0.85rem' }}>No analyses yet. Upload your first log!</div>
      ) : (
        history.map((item, i) => <HistoryItem key={item.id} item={item} isLast={i === history.length - 1} />)
      )}
    </div>
  );
};


/* ═══════════════════════════════════════
   MAIN DASHBOARD
   ═══════════════════════════════════════ */
export default function Dashboard() {
  const [analysisResult, setAnalysisResult] = useState(null);
  const [errorMsg, setErrorMsg] = useState(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [history, setHistory] = useState([]);
  const [historyLoading, setHistoryLoading] = useState(true);
  const { logout, user } = useAuth();
  const navigate = useNavigate();

  const fetchHistory = async () => {
    try {
      const res = await axios.get(`${API_BASE}/api/v1/logs/history?limit=8`);
      setHistory(res.data);
    } catch (err) { console.error("Failed to load history", err); }
    finally { setHistoryLoading(false); }
  };

  useEffect(() => { fetchHistory(); }, []);

  const handleUpload = async (file) => {
    try {
      setErrorMsg(null); setIsAnalyzing(true);
      const formData = new FormData();
      formData.append('file', file);
      const response = await axios.post(`${API_BASE}/api/v1/logs/upload`, formData, { headers: { 'Content-Type': 'multipart/form-data' } });
      setAnalysisResult(response.data);
      toast.success('Analysis complete');
      fetchHistory();
    } catch (err) {
      const msg = err.response?.data?.detail || "An error occurred during analysis.";
      setErrorMsg(msg); toast.error(msg); setAnalysisResult(null);
    } finally { setIsAnalyzing(false); }
  };

  const handleReset = () => { setAnalysisResult(null); setErrorMsg(null); };

  return (
    <div style={{ minHeight: '100vh' }}>
      {/* Nav */}
      <nav style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem 2.5rem', borderBottom: '1px solid var(--border-subtle)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <Terminal size={22} color="var(--accent)" strokeWidth={2.5} />
          <span style={{ fontSize: '1.15rem', fontWeight: 700, letterSpacing: '-0.5px' }}>LOG2ACTION</span>
        </div>
        <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
          <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginRight: '0.5rem' }}>{user?.email}</span>
          <ThemeToggle />
          {user?.is_admin && <button onClick={() => navigate('/admin')} className="btn-icon" title="Admin console"><Settings size={18} /></button>}
          <button onClick={logout} className="btn-icon" title="Sign out"><LogOut size={18} /></button>
        </div>
      </nav>

      {/* Single-column content */}
      <div style={{ maxWidth: '820px', margin: '0 auto', padding: '2rem 2rem' }}>
        <div style={{ marginBottom: '1.5rem' }}>
          <h1 style={{ fontSize: '1.75rem', fontWeight: 700, marginBottom: '0.3rem' }}>
            Log Analysis <span className="accent-text">Console</span>
          </h1>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.95rem' }}>Upload a log file — AI will diagnose it using your knowledge base.</p>
        </div>

        {errorMsg && (
          <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }}
            style={{ marginBottom: '1.25rem', padding: '0.75rem 1rem', borderRadius: '10px', background: 'rgba(217,79,79,0.08)', border: '1px solid rgba(217,79,79,0.2)', display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--error)', fontSize: '0.9rem' }}>
            <ShieldAlert size={18} /> {errorMsg}
          </motion.div>
        )}

        <AnimatePresence mode="wait">
          {!analysisResult ? (
            <UploadZone key="upload" onUpload={handleUpload} isAnalyzing={isAnalyzing} />
          ) : (
            <AnalysisResult key="result" result={analysisResult} onReset={handleReset} />
          )}
        </AnimatePresence>

        {/* History below — full width, compact */}
        <div style={{ marginTop: '2rem' }}>
          <HistorySidebar history={history} historyLoading={historyLoading} />
        </div>
      </div>
    </div>
  );
}
