name: Build and Push Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

permissions:
  id-token: write
  contents: read

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: false
          load: true
          tags: backend:local
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: backend:local
          format: table
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

      - name: Tag Image
        run: |
          docker tag backend:local \
          ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY_BACKEND }}:${{ github.sha }}

      - name: Push Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY_BACKEND }}:${{ github.sha }}
