name: Build, Scan and Push Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

permissions:
  id-token: write
  contents: read

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          load: true
          push: false
          tags: frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: frontend:${{ github.sha }}
          format: table
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "HIGH,CRITICAL"
      - name: Run Frontend Container
        run: |
          docker run -d \
            --name frontend-test \
            -p 8080:80 \
            frontend:${{ github.sha }}

      - name: Wait for Frontend
        run: sleep 5

      - name: Smoke Test Frontend
        run: |
          curl --fail http://localhost:8080/frontend-health

      - name: Stop Test Container
        if: always()
        run: |
          docker stop frontend-test
          docker rm frontend-test

      - name: Tag Image for Amazon ECR
        run: |
          docker tag frontend:${{ github.sha }} \
            ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY_FRONTEND }}:${{ github.sha }}

      - name: Push Image to Amazon ECR
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY_FRONTEND }}:${{ github.sha }}
